CREATE TABLE KH_STUDENT (
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE,
	CLUB_NO REFERENCES KH_CLUB
);

CREATE TABLE KH_CLUB (
	CLUB_NO NUMBER PRIMARY KEY,
	CLUB_NAME VARCHAR2(30) UNIQUE,
	CAPACITY NUMBER NOT NULL,
	EC_YN CHAR(1) CHECK(EC_YN IN ('Y','N')),
	ACTIVITY_TYPE VARCHAR2(100)
);

COMMENT ON COLUMN KH_STUDENT.STD_NO IS '학번';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE IS '나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR IS '전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학일';
COMMENT ON COLUMN KH_STUDENT.CLUB_NO IS '동아리 번호';

COMMENT ON COLUMN KH_CLUB.CLUB_NO IS '동아리 번호';
COMMENT ON COLUMN KH_CLUB.CLUB_NAME IS '동아리 이름';
COMMENT ON COLUMN KH_CLUB.CAPACITY IS '정원';
COMMENT ON COLUMN KH_CLUB.EC_YN IS '대외 활동 여부';
COMMENT ON COLUMN KH_CLUB.ACTIVITY_TYPE IS '활동성격';

CREATE SEQUENCE SEQ_STUDENT_NO NOCACHE;
CREATE SEQUENCE SEQ_CLUB_NO NOCACHE;

INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '시그마', 25, 'N', '수학 연구 및 문제 풀이 스터디');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '하모니밴드', 20, 'Y', '음악 밴드, 교내 공연 중심');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '디버그', 30, 'N', '프로그래밍 개발 스터디');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '도담', 20, 'N', '독서 및 문학 토론 동아리');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '클라우드', 30, 'Y', '클라우드·AI 프로젝트 대회 참가');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '네버기브업', 40, 'Y', '교내 스포츠·헬스 활동');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '아르테', 25, 'N', '미술·디자인 전시 활동');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '프론티어', 45, 'N', '여행 및 산악 탐험');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '라온', 25, 'Y', '댄스·공연 동아리');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '새벽빛', 30, 'Y', '사진전·영상제 외부 참여');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '리더스', 25, 'Y', '경제·경영 토론 및 교류');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '비상', 30, 'Y', '봉사활동 및 사회공헌');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '블루윙', 20, 'Y', '영어회화 및 해외 교류 활동');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '코그니션', 20, 'N', '심리학 실험 및 연구');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '톤앤무드', 30, 'N', '음악 감상 및 공연 기획');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '리더스', 25, 'Y', '경제·경영 토론 및 교류');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '비상', 30, 'Y', '봉사활동 및 사회공헌');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '블루윙', 20, 'Y', '영어회화 및 해외 교류 활동');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '코그니션', 20, 'N', '심리학 실험 및 연구');
INSERT INTO KH_CLUB VALUES(SEQ_CLUB_NO.NEXTVAL, '톤앤무드', 30, 'N', '음악 감상 및 공연 기획');



SELECT * FROM KH_CLUB;
COMMIT;

INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이현우', 25, '의학과', '2019-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김도현', 26, '기계공학과', '2019-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최예린', 25, '컴퓨터공학과', '2019-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '정하은', 25, '심리학과', '2019-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이서연', 24, '디자인학과', '2020-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '오지민', 24, '수학과', '2020-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '신재현', 25, '화학공학과', '2020-03-02', 5);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '장현우', 28, '건축학과', '2020-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박서연', 24, '간호학과', '2020-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '송지호', 24, '컴퓨터공학과', '2020-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤하은', 24, '경영학과', '2020-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '조민재', 24, '물리학과', '2020-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤서진', 26, '국어국문학과', '2020-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박상민', 27, '치의학과', '2020-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '문지우', 24, '심리학과', '2020-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김하늘', 24, '간호학과', '2020-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '오세훈', 23, '의학과', '2021-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '장도현', 23, '수학과', '2021-03-02', 5);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '하은호', 25, '영어영문학과', '2021-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '백서윤', 23, '기계공학과', '2021-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이준호', 24, '무역학과', '2021-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이명운', 22, '정치외교학과', '2022-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이현상', 22, '경제학과', '2022-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박도영', 22, '컴퓨터공학과', '2022-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김유나', 23, '경영학과', '2022-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이서윤', 22, '수학과', '2022-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이윤아', 21, '물리학과', '2023-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박민준', 24, '화학공학과', '2023-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '임수빈', 21, '간호학과', '2023-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이지아', 22, '국어국문학과', '2023-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최연우', 20, '영어영문학과', '2023-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박유진', 20, '경영학과', '2024-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '허예은', 21, '심리학과', '2024-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '연준서', 20, '경제학과', '2024-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '남궁소율', 22, '무역학과', '2024-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '계백순', 20, '신문방송학과', '2024-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤시은', 20, '디자인학과', '2024-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최아린', 19, '간호과', '2025-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최은서', 20, '의학과', '2025-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이도윤', 19, '건축학과', '2025-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박지아', 21, '수학과', '2023-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김태하', 22, '전자공학과', '2022-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이윤재', 23, '기계공학과', '2021-03-02', 1);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최윤서', 21, '음악학과', '2023-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이정훈', 23, '영어영문학과', '2021-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '한소율', 22, '간호학과', '2022-03-02', 2);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '정지현', 25, '컴퓨터공학과', '2020-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박태양', 23, '정보보안학과', '2021-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '오서준', 20, '소프트웨어학과', '2024-03-02', 3);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이혜진', 22, '국어국문학과', '2022-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤가영', 23, '철학과', '2021-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김현정', 20, '문헌정보학과', '2024-03-02', 4);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박재현', 23, 'AI학과', '2021-03-02', 5);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '조예린', 21, '데이터사이언스학과', '2023-03-02', 5);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '정우성', 24, '컴퓨터공학과', '2020-03-02', 5);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이채연', 21, '체육학과', '2023-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김예준', 22, '스포츠과학과', '2022-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박정우', 24, '사회체육학과', '2020-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '강채린', 21, '디자인학과', '2023-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '오유진', 23, '시각디자인학과', '2021-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박하율', 24, '패션디자인학과', '2020-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '남기현', 23, '지리학과', '2021-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이하린', 22, '관광학과', '2022-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김유정', 20, '산업디자인학과', '2024-03-02', 8);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '조하은', 21, '무용학과', '2023-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이시윤', 22, '심리학과', '2022-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김지후', 20, '공연예술학과', '2024-03-02', 9);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최유정', 22, '사진영상학과', '2022-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이도경', 24, '영화학과', '2020-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '문채원', 21, '디지털콘텐츠학과', '2023-03-02', 10);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤채린', 21, '영어영문학과', '2023-03-02', 11);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김하온', 23, '국제학과', '2021-03-02', 11);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '서은우', 22, '비즈니스영어학과', '2022-03-02', 11);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박소연', 22, '심리학과', '2022-03-02', 12);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김다현', 20, '사회복지학과', '2024-03-02', 12);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이민재', 24, '심리학과', '2020-03-02', 12);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '정하준', 21, '음악학과', '2023-03-02', 13);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '배유진', 23, '예술학과', '2021-03-02', 13);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '한지우', 20, '공연예술학과', '2024-03-02', 13);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '장민재', 24, '경영학과', '2020-03-02', 14);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '서지훈', 22, '경제학과', '2022-03-02', 14);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이민지', 21, '회계학과', '2023-03-02', 14);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '류정우', 25, '사회복지학과', '2020-03-02', 15);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김지연', 22, '사회학과', '2022-03-02', 15);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이수진', 20, '국제개발학과', '2024-03-02', 15);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최지호', 21, '경제학과', '2023-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '홍지민', 23, '법학과', '2021-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박하윤', 20, '언론정보학과', '2024-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김나래', 22, '경영학과', '2022-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이소민', 24, '국어국문학과', '2020-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '전하늘', 19, '간호학과', '2025-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '최서윤', 25, '정치외교학과', '2020-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이아영', 20, '디자인학과', '2024-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '강민지', 21, '컴퓨터공학과', '2023-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '박정민', 22, '의학과', '2022-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '송지우', 21, '무역학과', '2023-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '이서진', 19, '심리학과', '2025-03-02', NULL);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '한가온', 21, '시각디자인학과', '2023-03-02', 7);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '김도헌', 22, '체육학과', '2022-03-02', 6);
INSERT INTO KH_STUDENT VALUES(SEQ_STUDENT_NO.NEXTVAL, '윤지후', 24, '심리학과', '2020-03-02', 12);
COMMIT;

SELECT * FROM KH_STUDENT;


DELETE FROM KH_STUDENT
WHERE STD_NO = 11;



ROLLBACK;


SELECT * FROM KH_CLUB;














