-- 1.
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3.
SELECT PROFESSOR_NAME 교수이름, 
EXTRACT(YEAR FROM SYSDATE) - (1900 + SUBSTR(PROFESSOR_SSN, 1, 2)) 나이 
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름 FROM TB_PROFESSOR;

-- 5. 
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) 
- EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN , 1, 2), 'RR')) > 19;

